server:
  port: 8080
  tomcat:
    threads:
      max: 100                  # default 200
      min-spare: 5              # default 10
    max-connections: 8192       # default 8192
    accept-count: 100           # default 100
    connection-timeout: 30000   # 30초

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 3000
    p6spy:
      enabled: true
      appender: com.p6spy.engine.spy.appender.Slf4JLogger
      logMessageFormat:
        p6spy: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"

logging:
  config: classpath:log4j2.xml

demo:
  api: /api/v1


mylog:
  redis:
    host: localhost
    port: 6379